name: Email Security

product:
  title: Email Security (formerly Area 1)
  url: /email-security/
  group: Cloudflare One
  show: false

meta:
  title: Cloudflare Email Security (formerly Area 1) docs
  description: Cloudflare Email Security is a cloud based service that stops phishing attacks, the biggest cybersecurity threat, across all traffic vectors - email, web and network.
  author: "@cloudflare"
