name: Security

product:
  title: "Security dashboard"
  url: /security/
  show: false

meta:
  title: Security dashboard docs
  description: Documentation for the Security dashboard with an updated user interface.
  author: "@cloudflare"

externals:
  - title: Cloudflare homepage
    url: https://cloudflare.com
