content_dir: /src/content/docs
reviewer:
  custom_comment: |-
    Howdy and thanks for contributing to our repo. The Cloudflare team reviews new, external PRs within **two (2) weeks**. If it's been two weeks or longer without any movement, please tag the PR **Assignees** in a comment.

    We review internal PRs within **1 week**. If it's something urgent or has been sitting without a comment, start a thread in the *Developer Docs* space internally.
  enabled: true
  external_link_validation:
    enabled: false
    check_status_upon_review_failure: neutral
  summarize_pull_request:
    enabled: true
  vale_style_guide:
    check_status_upon_review_failure: neutral
    enabled: true
  custom_style_guide:
    enabled: false
    path_to_style_guide_dir: ".hyperlint/automations/styles/plain-text-style-checks/"
    check_status_upon_review_failure: neutral
  limit_num_reviews: 2
  limit_num_comments: 5
automation:
  custom_style_guide:
    enabled: true
    path_to_style_guide_dir: ".hyperlint/automations/styles/plain-text-style-checks/"
  enabled: true
  vale_style_guide:
    enabled: true
    path_to_vale_ini_file: ".hyperlint/.vale.ini"
